baseURL = "https://www.boss-net.github.io/risksdrivers/"
title = "risksDrivers"
enableRobotsTXT = true
theme = ["compose"] # loading from local
enableGitInfo = true
# Google Analytics
googleAnalytics = "G-33C5VXLWPQ"
[outputs]
  home = ["HTML", "RSS","JSON"]
